# Generated by Django 3.2.8 on 2022-02-12 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Akun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, unique=True)),
                ('nama', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Soal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('timer', models.DurationField()),
                ('tanggal', models.DateTimeField()),
                ('link_soal', models.URLField()),
                ('attempts', models.IntegerField(null=True)),
                ('akun_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='togra.akun')),
            ],
        ),
        migrations.CreateModel(
            name='Peserta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_peserta', models.CharField(max_length=50)),
                ('nilai', models.IntegerField(null=True)),
                ('soal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='togra.soal')),
            ],
        ),
        migrations.CreateModel(
            name='Pertanyaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(max_length=10)),
                ('instruksi', models.TextField()),
                ('jawaban_benar', models.TextField()),
                ('soal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='togra.soal')),
            ],
        ),
        migrations.CreateModel(
            name='Jawaban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jawaban', models.TextField(null=True)),
                ('pembahasan', models.TextField()),
                ('pertanyaan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='togra.pertanyaan')),
                ('peserta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='togra.peserta')),
            ],
        ),
    ]
