# Generated by Django 3.2.8 on 2022-02-19 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('togra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soal',
            name='akun_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='togra.akun'),
        ),
        migrations.AlterField(
            model_name='soal',
            name='link_soal',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='soal',
            name='timer',
            field=models.DurationField(null=True),
        ),
    ]
