# Generated by Django 3.2.8 on 2022-03-11 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togra', '0002_auto_20220219_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='akun',
            name='username',
        ),
        migrations.AlterField(
            model_name='jawaban',
            name='pembahasan',
            field=models.TextField(null=True),
        ),
    ]
