# Generated by Django 3.2.8 on 2022-04-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togra', '0003_auto_20220311_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='peserta',
            name='attemptdate',
            field=models.DateTimeField(null=True),
        ),
    ]
