# Generated by Django 3.2.8 on 2022-04-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togra', '0004_peserta_attemptdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pertanyaan',
            name='tipe',
        ),
        migrations.RemoveField(
            model_name='soal',
            name='tanggal',
        ),
        migrations.AddField(
            model_name='soal',
            name='tipe',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
