# Generated by Django 3.2.8 on 2022-04-02 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togra', '0005_auto_20220402_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='pertanyaan',
            name='pyfile',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='pertanyaan',
            name='jawaban_benar',
            field=models.TextField(null=True),
        ),
    ]
