# Generated by Django 3.2.8 on 2022-04-02 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togra', '0006_auto_20220402_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soal',
            name='timer',
            field=models.TimeField(null=True),
        ),
    ]
