# Generated by Django 3.2.8 on 2022-04-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togra', '0009_alter_soal_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pertanyaan',
            name='jawaban_benar',
            field=models.TextField(default='No Answer', null=True),
        ),
        migrations.AlterField(
            model_name='pertanyaan',
            name='pyfile',
            field=models.URLField(default='!', null=True),
        ),
    ]
