# Generated by Django 3.2.8 on 2022-04-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togra', '0010_auto_20220403_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pertanyaan',
            name='jawaban_benar',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pertanyaan',
            name='pyfile',
            field=models.FileField(null=True, upload_to='python/'),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='attemptdate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
