# Generated by Django 3.2.8 on 2022-04-02 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togra', '0011_auto_20220403_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pertanyaan',
            name='jawaban_benar',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='pertanyaan',
            name='pyfile',
            field=models.FileField(default='No Data', null=True, upload_to='python/'),
        ),
    ]
