# Generated by Django 3.2.8 on 2022-04-04 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togra', '0014_jawaban_pyfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soal',
            name='timer',
            field=models.TimeField(default='00:00:00', null=True),
        ),
    ]
