# Generated by Django 3.2.8 on 2022-04-04 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togra', '0017_alter_soal_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soal',
            name='timer',
            field=models.TimeField(null=True),
        ),
    ]
