# Generated by Django 3.2.8 on 2022-04-10 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togra', '0018_alter_soal_timer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soal',
            name='akun_id',
        ),
        migrations.AddField(
            model_name='soal',
            name='akun',
            field=models.TextField(null=True),
        ),
    ]
