# Generated by Django 3.2.8 on 2022-04-10 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('togra', '0019_auto_20220410_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soal',
            name='akun',
        ),
        migrations.AddField(
            model_name='soal',
            name='akun_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='togra.akun'),
        ),
    ]
