# Generated by Django 3.2.8 on 2022-04-10 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('togra', '0021_alter_soal_akun_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soal',
            old_name='akun_id',
            new_name='akun',
        ),
    ]
