# Generated by Django 3.2.8 on 2022-04-10 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('togra', '0022_rename_akun_id_soal_akun'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Akun',
        ),
    ]
