# Generated by Django 3.2.8 on 2022-04-10 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('togra', '0023_delete_akun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soal',
            name='akun',
        ),
    ]
