# Generated by Django 3.2.8 on 2022-04-10 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togra', '0024_remove_soal_akun'),
    ]

    operations = [
        migrations.AddField(
            model_name='soal',
            name='user',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
