# Generated by Django 3.2.8 on 2022-04-10 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togra', '0025_soal_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soal',
            name='user',
            field=models.TextField(null=True),
        ),
    ]
