"""
Django settings for autograde project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!4=l3%s9(b1)*jb*u_x8^*c0he-^z92tl(1b@i-@1mlc1!7yjl'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [ 'localhost','127.0.0.1', '1c71-182-2-71-48.ngrok.io']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'togra',
    'bootstrap_datepicker_plus',
    'tempus_dominus',
    'lti_provider',
    'widget_tweaks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
]

ROOT_URLCONF = 'autograde.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['togra/template'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.media',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'autograde.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'autograde',
        'USER': 'postgres',
        'PASSWORD': 'master102',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [ BASE_DIR, 'static' ]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTHENTICATION_BACKENDS = [
  'django.contrib.auth.backends.ModelBackend',
  'lti_provider.auth.LTIBackend',
]

PYLTI_CONFIG = {
    'consumers': {
        'rtey23': {
            'secret': 'dhabty3'
        }
    }
}

SESSION_ENGINE = "django.contrib.sessions.backends.signed_cookies"

SESSION_COOKIE_SAMESITE = None

SESSION_COOKIE_SECURE = True

SESSION_COOKIE_HTTPONLY = True

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTOCOL', 'https')

LTI_TOOL_CONFIGURATION = {
    'title': 'Sample LTI Tool',
    'description': 'This tool includes launch, navigation and assignments',
    'launch_url': 'lti/',
    'embed_url': '',  # @todo - add an editor embed example
    'embed_icon_url': '',
    'embed_tool_id': '',
    'landing_url': '/',
    'navigation': True,
    'new_tab': True,
    'course_aware': False,
    'frame_width': 1024,
    'frame_height': 1024,
    'assignments': {
        '1' : '/assignment/1/',
        '2' : '/assignment/2/',
        '3' : '/assignment/3/',
        '4' : '/assignment/4/',
        '5' : '/assignment/5/',
        '6' : '/assignment/6/',
        '7' : '/assignment/7/',
        '8' : '/assignment/8/',
        '9' : '/assignment/9/',
        '10' : '/assignment/10/',
        '11' : '/assignment/11/',
        '12' : '/assignment/12/',
        '13' : '/assignment/13/',
        '14' : '/assignment/14/',
        '15' : '/assignment/15/',
        '16' : '/assignment/16/',
        '17' : '/assignment/17/',
        '18' : '/assignment/18/',
        '19' : '/assignment/19/',
        '20' : '/assignment/20/',
        '21' : '/assignment/21/',
        '22' : '/assignment/22/',
        '23' : '/assignment/23/',
        '24' : '/assignment/24/',
        '25' : '/assignment/25/',
        '26' : '/assignment/26/',
        '27' : '/assignment/27/',
        '28' : '/assignment/28/',
        '29' : '/assignment/29/',
        '30' : '/assignment/30/',
        '31' : '/assignment/31/',
        '32' : '/assignment/32/',
        '33' : '/assignment/33/',
        '34' : '/assignment/34/',
        '35' : '/assignment/35/',
        '36' : '/assignment/36/',
        '37' : '/assignment/37/',
        '38' : '/assignment/38/',
        '39' : '/assignment/39/',
        '40' : '/assignment/40/',
        '41' : '/assignment/41/',
        '42' : '/assignment/42/',
        '43' : '/assignment/43/',
        '44' : '/assignment/44/',
        '45' : '/assignment/45/',
        '46' : '/assignment/46/',
        '47' : '/assignment/47/',
        '48' : '/assignment/48/',
        '49' : '/assignment/49/',
        '50' : '/assignment/50/',
    }
}

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_REDIRECT_URL = 'home'

LOGIN_URL = 'login'